apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "*/2 * * * *" # 매 2분마다 실행
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: hello-cronjob
        spec:
          containers:
          - name: hello
            image: busybox
            command: ["sh", "-c", "echo Hello, Kubernetes from CronJob! && sleep 60"]
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

