apiVersion: batch/v1
kind: Job
metadata:
  name: scheduled-job
spec:
  template:
    metadata:
      labels:
        app: scheduled-job
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["sh", "-c", "sleep 30 && echo Hello, Kubernetes!"]
      restartPolicy: Never
  backoffLimit: 4

