apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3
  selector:
    app: webui
    ver: "1.1"
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
        ver: "1.1"
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
